# Generated by Django 4.1 on 2022-09-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stripe_product",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
